dist: xenial

language: go

go: 
  - 1.11.x

sudo: required

service:
  - docker  
  
install: true

before_script:
  - chmod a+x build/build.sh
  - ./build/build.sh

  - pushd .
  - cd /home/travis/gopath/src/github.com/h3copen/h3cfibservice/fibhandler
  - mv /home/travis/gopath/src/github.com/h3copen/h3copenr/dockerfile_fib .
  - docker build -f dockerfile_fib -t fib:test .
  - popd
  - chmod +x build/test.sh
  
script:
  - ./build/test.sh
