dist: xenial

language: go

go: 
  - 1.11.x

sudo: required

service:
  - docker  
  
install: true

before_script:
  - chmod a+x build/build.sh
  - ./build/build.sh
  - pushd .
  - cd /home/travis/gopath/src/github.com/h3copen/h3cfibservice/fibhandler
  - docker pull ubuntu:16.04
  - docker run -itd --name ubuntu ubuntu:16.04 /bin/bash 
  - docker cp fibhandler ubuntu:/bin
  - docker commit ubuntu fib:test
  - popd
  - docker pull lmke/h3c_openr:v2
  - docker run -itd --name complie_openr lmke/h3c_openr:v3  bash
  - docker exec -it complie_openr sh -c " git clone https://github.com/facebook/openr.git && cd /openr/build \
                                          && sed -i \"s/sudo//g \"  build_openr.sh  && ./build_openr.sh"

  - chmod +x build/test.sh
  
script:
  - ./build/test.sh
