dist: xenial

language: go

go: 
  - 1.11.x

sudo: required

service:
  - docker 
  
before_install:

install: true

before_script:
  - pwd
  - chmod a+x build/build.sh
  - ./build/build.sh
  - cd /home/travis/gopath/src/github.com/h3copen/h3cfibservice/fibhandler
  - docker pull ubuntu:16.04
  - docker images
  - docker run -itd --name ubuntu ubuntu:16.04 /bin/bash 
  - docker ps
  - docker cp fibhandler ubuntu:/ 
  - docker exec ubuntu sh -c "ls -l"
  - docker exec ubuntu sh -c "./fibhandler"

  
script:
