dist: xenial

language: go

go: 
  - 1.11.x

sudo: required

service:
  - docker  
  
install: true

before_script:
  - chmod a+x build/build.sh
  - ./build/build.sh

  - pushd .
  - cd /home/travis/gopath/src/github.com/h3copen/h3cfibservice/fibhandler
  - mv /home/travis/gopath/src/github.com/h3copen/h3copenr/dockerfile_fib .
  - docker build -f dockerfile_fib -t fib:test .
  - popd
  - docker pull lmke/h3c_openr:v5
  - docker run -itd --name complie_openr lmke/h3c_openr:v5  bash
  - docker exec -it complie_openr sh -c " git clone https://github.com/facebook/openr.git"
  - if [ $? -eq 0 ]
  -  then
  -   docker exec complie_openr sh -c "cd /openr && git log | head -1"  >> commit.id.log
  -   docker cp complie_openr:/usr/local/sbin/openr .
  -   docker build -f dockerfile_openr -t openr:test .
  - else
  -   exit 1
  - fi
    

  - chmod +x build/test.sh
  
script:
  - ./build/test.sh
